name: wheelie

services:
  # backend:
  #   image: ethan.lo/wheelie
  #   build:
  #     context: .
  #     target: dev
  #   env_file:
  #     - path: .env
  #   ports:
  #     - "3000-3001:3000-3001"

  # azure-sql-edge:
  #   image: mcr.microsoft.com/azure-sql-edge
  #   container_name: azure-sql-edge
  #   restart: always
  #   expose:
  #     - '1433'
  #   ports:
  #     - "1433:1433"
  #   environment:
  #     ACCEPT_EULA: 1
  #     MSSQL_SA_PASSWORD: yourStrong(!)Password
  #   volumes:
  #     - azure-sql-edge-data:/var/opt/mssql
  #     - ./db/config/mssql.conf:/var/opt/mssql/mssql.conf:ro

  postgres:
    image: postgres:14
    container_name: postgres
    restart: always
    expose:
      - '5432'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: wheelie
      POSTGRES_PASSWORD: wheelie
      POSTGRES_DB: wheelie
    volumes:
      - postgres:/var/lib/postgresql/data
  

volumes:
  # azure-sql-edge-data:
  postgres:
